repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
    -   id: mypy
        additional_dependencies:
        -   types-python-dateutil
        -   types-requests
-   repo: local
    hooks:
    -   id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: python -m nbconvert --ClearOutputPreprocessor.enabled=True --inplace
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
    -   id: nbqa-black
        additional_dependencies: [black==22.3.0]
    -   id: nbqa-isort
