"project_id": "8"
"base_url": "https://microcovid.crowdin.com"
"preserve_hierarchy": true

"files": [
  {
    "source": "/src/locales/en.json",
    "translation": "/src/locales/%two_letters_code%.json"
  }
]
