#!/bin/bash

# TODO(blanchardjeremy): Need to check for the existence of the GitHub CLI before running

git checkout main
git pull
git push origin --delete auto-update-prevalence
git branch -D auto-update-prevalence
git checkout -b auto-update-prevalence
source .venv/bin/activate
source .secure-keys
python3 update_prevalence.py

# Needed in order to fix some lint errors that come up from the JSON generated by update_prevalence.py
eslint src --fix

# Only proceed if files have have been changed
# TODO(blanchardjeremy): Could use better error checking
if [[ `git status --porcelain` ]]; then
  TODAY=`date +%Y-%m-%d`
  git add -A
  git commit -am "Automatic prevalence update $TODAY"
  git push
  PR_URL=`gh pr create --fill`
  echo "Pull request URL: $PR_URL"
  if [[ ! $PR_URL = "" ]]; then
    gh pr merge --auto --delete-branch --squash "$PR_URL"
  else
    echo "ERROR: No pull request URL generated"
    exit 2
  fi
else
  echo "No changes to add"
fi
