name: Bot Merge

on:
  workflow_dispatch:
    inputs:
      prnum:
        description: 'Pull Request Number'
        required: true

jobs:
  bot-merge:
    runs-on: ubuntu-latest
    steps:

    - name: Get INSTALLATION_ACCESS_TOKEN from microCOVID Automation app
      uses: navikt/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ secrets.MICROCOVID_BOT_PRIVATE_KEY }}
        app-id: ${{ secrets.MICROCOVID_BOT_APP_ID }}

    - name: Checkout git repo (with full history)
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        token: ${{ steps.get-token.outputs.token }}
        fetch-depth: 0
        
    - name: Run the merge command
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
      run: gh pr merge --delete-branch --squash ${{ github.event.inputs.prnum }}
