name: Lint fix

# Can be run manually to fix lint server side on a branch of your choice
on:
  workflow_dispatch:

jobs:
  lint-fix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - run: yarn fix

    - uses: navikt/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ secrets.MICROCOVID_BOT_PRIVATE_KEY }}
        app-id: ${{ secrets.MICROCOVID_BOT_APP_ID }}

    # - uses: EndBug/add-and-commit@v7
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_JEREMY }}
    #   with:
    #     message: "GitHub Action lint fix auto-commit"
    #     default_author: github_actions

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
      run: |
        git config --global user.name "microCOVID Automation"
        git config --global user.email info@microcovid.org
        git commit -am "Automatically committing lint fix changes"
        git push --set-upstream


    # - name: Wait for status checks
    #   id: waitforstatuschecks
    #   uses: WyriHaximus/github-action-wait-for-status@v1.4
    #   with:
    #     ignoreActions: automerge
    #     checkInterval: 13
    #   env:
    #     GITHUB_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN_JEREMY }}"

    

    - name: Set to auto merge
      if: steps.waitforstatuschecks.outputs.status == 'success'
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
      run: gh pr merge --auto --delete-branch --squash 1060
