name: Lint fix

# Can be run manually to fix lint server side on a branch of your choice
on:
  workflow_dispatch:

jobs:
  lint-fix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - run: yarn fix

    - uses: navikt/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ secrets.MICROCOVID_BOT_PRIVATE_KEY }}
        app-id: ${{ secrets.MICROCOVID_BOT_APP_ID }}


    - run: echo "${{ github.action }}""

    # - name: Commit changes
    #   env:
    #     GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
    #   run: |
    #     git config --global user.name "microCOVID Automation"
    #     git config --global user.email info@microcovid.org
    #     git commit -am "Automatically committing lint fix changes"
    #     git push --set-upstream
    
    # - name: Set to auto merge
    #   env:
    #     GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
    #   run: gh pr merge --auto --delete-branch --squash 1060
