name: Lint fix

# Can be run manually to fix lint server side on a branch of your choice
on:
  workflow_dispatch:

jobs:
  lint-fix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - run: yarn fix

    - uses: navikt/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ secrets.MICROCOVID_BOT_PRIVATE_KEY }}
        app-id: ${{ secrets.MICROCOVID_BOT_APP_ID }}

    - uses: EndBug/add-and-commit@v7
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
      with:
        message: "GitHub Action lint fix auto-commit"
        default_author: github_actions
